"""
Email Integration System
Send/receive emails, inbox management, and email templates
"""
import smtplib
import imaplib
import email
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from email.mime.base import MIMEBase
from email import encoders
from datetime import datetime
import os
from typing import List, Dict, Optional


class EmailService:
    """Complete email integration system"""
    
    def __init__(self):
        # Email configuration (from environment or config)
        self.smtp_server = os.getenv('SMTP_SERVER', 'smtp.gmail.com')
        self.smtp_port = int(os.getenv('SMTP_PORT', 587))
        self.imap_server = os.getenv('IMAP_SERVER', 'imap.gmail.com')
        self.imap_port = int(os.getenv('IMAP_PORT', 993))
        
        self.email_address = os.getenv('EMAIL_ADDRESS', '[email]')
        self.email_password = os.getenv('EMAIL_PASSWORD', '[password]')
        
        self.inbox = []
        self.sent_emails = []
        self.drafts = []
        
        # Email templates
        self.templates = {
            'welcome': {
                'subject': 'Welcome to AKIRA AI System',
                'body': '''Hello {name},

Welcome to AKIRA AI System! We're excited to have you on board.

Your account has been successfully created and you can now access all features.

Best regards,
AKIRA Team'''
            },
            'notification': {
                'subject': 'AKIRA Notification: {title}',
                'body': '''Hello,

{message}

Time: {timestamp}

This is an automated notification from AKIRA AI System.'''
            },
            'reminder': {
                'subject': 'Reminder: {title}',
                'body': '''Hello,

This is a reminder about: {title}

Details: {details}

Time: {time}

Best regards,
AKIRA AI System'''
            },
            'alert': {
                'subject': '🚨 Alert: {alert_type}',
                'body': '''ALERT NOTIFICATION

Type: {alert_type}
Priority: {priority}
Time: {timestamp}

Details:
{details}

Please take appropriate action.

AKIRA AI System'''
            },
            'report': {
                'subject': 'Daily Report - {date}',
                'body': '''Daily Report for {date}

Summary:
{summary}

Key Metrics:
{metrics}

Recommendations:
{recommendations}

Generated by AKIRA AI System'''
            }
        }
    
    def send_email(self, to_email: str, subject: str, body: str, 
                   html: bool = False, attachments: List[str] = None) -> Dict:
        """Send an email via Gmail SMTP"""
        try:
            # Create message
            msg = MIMEMultipart('alternative')
            msg['From'] = self.email_address
            msg['To'] = to_email
            msg['Subject'] = subject
            msg['Date'] = email.utils.formatdate(localtime=True)
            
            # Add body
            if html:
                msg.attach(MIMEText(body, 'html'))
            else:
                msg.attach(MIMEText(body, 'plain'))
            
            # Add attachments
            if attachments:
                for file_path in attachments:
                    if os.path.exists(file_path):
                        with open(file_path, 'rb') as f:
                            part = MIMEBase('application', 'octet-stream')
                            part.set_payload(f.read())
                            encoders.encode_base64(part)
                            part.add_header('Content-Disposition', 
                                          f'attachment; filename={os.path.basename(file_path)}')
                            msg.attach(part)
            
            # Try to send via real SMTP
            try:
                # Connect to Gmail SMTP server
                server = smtplib.SMTP(self.smtp_server, self.smtp_port)
                server.starttls()  # Enable TLS encryption
                
                # Login to Gmail
                server.login(self.email_address, self.email_password)
                
                # Send email
                server.send_message(msg)
                server.quit()
                
                print(f"✅ Email sent successfully to {to_email}")
                print(f"   Subject: {subject}")
                
                # Log sent email
                sent_email = {
                    'id': len(self.sent_emails) + 1,
                    'to': to_email,
                    'subject': subject,
                    'body': body,
                    'timestamp': datetime.now().isoformat(),
                    'status': 'sent',
                    'attachments': attachments or []
                }
                self.sent_emails.append(sent_email)
                
                return {
                    'success': True,
                    'message': 'Email sent successfully via Gmail',
                    'email_id': sent_email['id']
                }
                
            except smtplib.SMTPAuthenticationError:
                print("⚠️  Gmail authentication failed. Using simulation mode.")
                print("   To send real emails, configure EMAIL_ADDRESS and EMAIL_PASSWORD in .env")
                print("   For Gmail, use an App Password: https://myaccount.google.com/apppasswords")
                
                # Fall back to simulation
                print(f"📧 Email simulated to {to_email}")
                print(f"   Subject: {subject}")
                
                sent_email = {
                    'id': len(self.sent_emails) + 1,
                    'to': to_email,
                    'subject': subject,
                    'body': body,
                    'timestamp': datetime.now().isoformat(),
                    'status': 'simulated',
                    'attachments': attachments or []
                }
                self.sent_emails.append(sent_email)
                
                return {
                    'success': True,
                    'message': 'Email simulated (configure Gmail credentials for real sending)',
                    'email_id': sent_email['id']
                }
            
        except Exception as e:
            print(f"❌ Email error: {e}")
            return {
                'success': False,
                'message': str(e)
            }
    
    def send_from_template(self, template_name: str, to_email: str, 
                          variables: Dict) -> Dict:
        """Send email using a template"""
        if template_name not in self.templates:
            return {
                'success': False,
                'message': f'Template {template_name} not found'
            }
        
        template = self.templates[template_name]
        
        # Format subject and body with variables
        subject = template['subject'].format(**variables)
        body = template['body'].format(**variables)
        
        return self.send_email(to_email, subject, body)
    
    def receive_emails(self, folder: str = 'INBOX', limit: int = 50) -> List[Dict]:
        """Receive emails from inbox (simulated)"""
        # In real implementation, this would connect to IMAP server
        # For now, return simulated inbox
        
        simulated_emails = [
            {
                'id': 1,
                'from': '[email]',
                'subject': 'Welcome to AKIRA',
                'body': 'Thank you for using AKIRA AI System...',
                'timestamp': datetime.now().isoformat(),
                'read': False,
                'starred': False,
                'folder': 'INBOX'
            },
            {
                'id': 2,
                'from': '[email]',
                'subject': 'System Update Available',
                'body': 'A new system update is available...',
                'timestamp': datetime.now().isoformat(),
                'read': True,
                'starred': False,
                'folder': 'INBOX'
            }
        ]
        
        self.inbox = simulated_emails
        return simulated_emails[:limit]
    
    def get_inbox(self, unread_only: bool = False) -> List[Dict]:
        """Get inbox emails"""
        if unread_only:
            return [email for email in self.inbox if not email['read']]
        return self.inbox
    
    def get_sent_emails(self, limit: int = 50) -> List[Dict]:
        """Get sent emails"""
        return self.sent_emails[-limit:]
    
    def mark_as_read(self, email_id: int) -> bool:
        """Mark email as read"""
        for email in self.inbox:
            if email['id'] == email_id:
                email['read'] = True
                return True
        return False
    
    def mark_as_unread(self, email_id: int) -> bool:
        """Mark email as unread"""
        for email in self.inbox:
            if email['id'] == email_id:
                email['read'] = False
                return True
        return False
    
    def star_email(self, email_id: int) -> bool:
        """Star an email"""
        for email in self.inbox:
            if email['id'] == email_id:
                email['starred'] = not email.get('starred', False)
                return True
        return False
    
    def delete_email(self, email_id: int) -> bool:
        """Delete an email"""
        self.inbox = [email for email in self.inbox if email['id'] != email_id]
        return True
    
    def search_emails(self, query: str, folder: str = 'all') -> List[Dict]:
        """Search emails"""
        query_lower = query.lower()
        results = []
        
        search_list = self.inbox if folder == 'INBOX' else self.inbox + self.sent_emails
        
        for email in search_list:
            if (query_lower in email['subject'].lower() or 
                query_lower in email['body'].lower() or
                query_lower in email.get('from', '').lower()):
                results.append(email)
        
        return results
    
    def create_draft(self, to_email: str, subject: str, body: str) -> Dict:
        """Create email draft"""
        draft = {
            'id': len(self.drafts) + 1,
            'to': to_email,
            'subject': subject,
            'body': body,
            'created_at': datetime.now().isoformat(),
            'updated_at': datetime.now().isoformat()
        }
        
        self.drafts.append(draft)
        
        return draft
    
    def get_drafts(self) -> List[Dict]:
        """Get all drafts"""
        return self.drafts
    
    def send_draft(self, draft_id: int) -> Dict:
        """Send a draft email"""
        for draft in self.drafts:
            if draft['id'] == draft_id:
                result = self.send_email(draft['to'], draft['subject'], draft['body'])
                if result['success']:
                    self.drafts.remove(draft)
                return result
        
        return {'success': False, 'message': 'Draft not found'}
    
    def get_email_statistics(self) -> Dict:
        """Get email statistics"""
        total_inbox = len(self.inbox)
        unread_count = len([e for e in self.inbox if not e['read']])
        starred_count = len([e for e in self.inbox if e.get('starred', False)])
        total_sent = len(self.sent_emails)
        total_drafts = len(self.drafts)
        
        return {
            'inbox': {
                'total': total_inbox,
                'unread': unread_count,
                'starred': starred_count
            },
            'sent': total_sent,
            'drafts': total_drafts,
            'total_emails': total_inbox + total_sent
        }
    
    def add_template(self, name: str, subject: str, body: str) -> bool:
        """Add custom email template"""
        self.templates[name] = {
            'subject': subject,
            'body': body
        }
        return True
    
    def get_templates(self) -> Dict:
        """Get all email templates"""
        return self.templates
    
    def send_bulk_email(self, recipients: List[str], subject: str, 
                       body: str, personalize: bool = False) -> Dict:
        """Send bulk emails"""
        results = {
            'success': 0,
            'failed': 0,
            'total': len(recipients)
        }
        
        for recipient in recipients:
            result = self.send_email(recipient, subject, body)
            if result['success']:
                results['success'] += 1
            else:
                results['failed'] += 1
        
        return results


# Global instance
email_service = EmailService()


if __name__ == '__main__':
    print("="*60)
    print("📧 Email Integration System - Test")
    print("="*60)
    
    # Check if Gmail is configured
    if email_service.email_address == '[email]':
        print("\n⚠️  Gmail not configured!")
        print("   To send real emails:")
        print("   1. Read GMAIL_SETUP_GUIDE.md")
        print("   2. Configure EMAIL_ADDRESS and EMAIL_PASSWORD in .env")
        print("   3. Use Gmail App Password (not regular password)")
        print("\n   Running in simulation mode...\n")
    else:
        print(f"\n✅ Gmail configured: {email_service.email_address}")
        print("   Emails will be sent via Gmail SMTP\n")
    
    # Test sending email
    result = email_service.send_email(
        to_email='[email]',
        subject='Test Email from AKIRA',
        body='This is a test email from AKIRA AI System.'
    )
    print(f"\n{'✅' if result['success'] else '❌'} Email result: {result['message']}")
    
    # Test template email
    result = email_service.send_from_template(
        template_name='welcome',
        to_email='[email]',
        variables={'name': 'John Doe'}
    )
    print(f"{'✅' if result['success'] else '❌'} Template email: {result['message']}")
    
    # Test inbox
    inbox = email_service.receive_emails()
    print(f"\n📥 Inbox: {len(inbox)} emails")
    
    # Test statistics
    stats = email_service.get_email_statistics()
    print(f"\n📊 Statistics:")
    print(f"   Inbox: {stats['inbox']['total']} ({stats['inbox']['unread']} unread)")
    print(f"   Sent: {stats['sent']}")
    print(f"   Drafts: {stats['drafts']}")
    
    print("\n" + "="*60)
    print("📧 TO SEND REAL EMAILS:")
    print("="*60)
    print("1. Read: GMAIL_SETUP_GUIDE.md")
    print("2. Or: GMAIL_QUICK_SETUP.txt for quick steps")
    print("3. Configure .env with your Gmail credentials")
    print("4. Restart AKIRA")
    print("5. Send emails via web interface or API")
    print("="*60)
    
    print("\n✅ Email system tested!")

